### ISSUE TITLE
Guide to Drawing Figures?

### ISSUE THREAD

**Issue by QiyaoWei** [srush/LLM-Talk#1]
Dear Professor Rush,

Many thanks for this awesome talk! Aside from the great content, I am also fascinated by the figures and animations created in this talk! Therefore, I was wondering whether you could share how you made the slides? Was it through powerpoint? What was the font that you used? Where did those animated icons (e.g. small robot) come from? Thanks again!

**Comment by srush** [comment]
Nothing special! I made it by hand on excalidraw+ which has a slides mode. There are actually no animations, just 130 slides. The robot comes from The Noun Project and I used her in my GPU puzzles before.

**Comment by QiyaoWei** [comment]
Thanks!
